# -*- coding: utf-8 -*-
"""Útvonal-definíciók: útpontok (a router ezek között keres gravel-barát utat),
leírások, értékelések, indulási módok, kiemelt pontok és októberi figyelmeztetések.

Útpont-formátum: (lat, lon) vagy (lat, lon, "Név", "típus") – a névvel ellátott
pontok a kiemelt pontok listájába is bekerülnek.  Típusok: lake, hut, gorge,
view, history, town, station, pass.
"""

HOTEL = (47.7269, 12.8835)

STATIONS = {
    "brh":   ("Bad Reichenhall Hbf", 47.73091, 12.88199, 0),
    "kirch": ("Bad Reichenhall-Kirchberg", 47.72030, 12.87420, 3),
    "piding": ("Piding", 47.75964, 12.91137, 6),
    "hammerau": ("Hammerau", 47.79621, 12.94655, 10),
    "freil": ("Freilassing", 47.83661, 12.97710, 15),
    "sbg":   ("Salzburg Hbf", 47.81250, 13.04529, 30),
    "laufen": ("Laufen (Obb)", 47.93451, 12.92233, 45),
    "bgd":   ("Berchtesgaden Hbf", 47.62628, 12.99931, 30),
    "golling": ("Golling-Abtenau", 47.60024, 13.16465, 75),
    "hallein": ("Hallein", 47.68493, 13.09916, 55),
    "teis":  ("Teisendorf", 47.84927, 12.83427, 35),
    "traun": ("Traunstein", 47.86944, 12.63897, 60),
    "ruhp":  ("Ruhpolding", 47.76214, 12.64879, 95),
    "bischof": ("Bischofswiesen", 47.65197, 12.96038, 22),
}

PARKINGS = {
    "thumsee": ("Parkplatz Seewirt, Thumsee", 47.71930, 12.82193, 8),
    "inzell":  ("Inzell, P4 (Zentrum)", 47.76217, 12.75172, 20),
    "anger":   ("Anger, Scheiterparkplatz", 47.80218, 12.85599, 12),
    "teis":    ("Teisendorf, P5 (Zentrum)", 47.85059, 12.82060, 20),
    "hallthurm": ("Wanderparkplatz Hallthurm", 47.69664, 12.93537, 10),
    "hintersee": ("Parkplatz Hintersee West (Ramsau)", 47.60427, 12.84969, 30),
    "wimbach": ("Parkplatz Wimbachbrücke (Ramsau)", 47.60300, 12.92315, 27),
    "koenigssee": ("Parkplatz Königssee (P1)", 47.59179, 12.98946, 30),
    "bgd":     ("Berchtesgaden, Schießstättparkplatz", 47.63006, 13.00572, 25),
    "lofer":   ("Lofer, Parkplatz Zentrum", 47.58680, 12.69497, 30),
    "unken":   ("Unken, Parkplatz Ortsmitte", 47.64853, 12.73023, 22),
    "freil":   ("Freilassing, Bahnhof (P+R)", 47.83623, 12.97645, 15),
    "laufen":  ("Laufen, Parkplatz Amtsgericht", 47.93766, 12.93110, 25),
    "hallein": ("Hallein, Parkplatz Pernerinsel", 47.68250, 13.09700, 30),
    "untersberg": ("Parkplatz Untersbergbahn, St. Leonhard", 47.72508, 13.04174, 25),
    "ruhp":    ("Ruhpolding Nord", 47.76490, 12.64377, 30),
    "grossgmain": ("Großgmain, Parkplatz Plainburg", 47.72516, 12.92281, 7),
}

BIKE_TICKET_DE = "Bajor regionális vonaton (BLB, S-Bahn, RB) kerékpár-napijegy kell (DB Fahrradtageskarte Bayern); a hely korlátozott, hétvégén zsúfolt lehet."
BIKE_TICKET_AT = "Osztrák (ÖBB/S-Bahn Salzburg) szakaszon külön Fahrrad-Tageskarte kell; a határon átnyúló járaton mindkét fél szabálya érvényes – vedd meg előre az appban."

ROUTES = [
# ------------------------------------------------------------------ 1
dict(id="thumsee-listsee", name="Thumsee bemelegítő kör", creative=False, rating=4,
 inspired=None,
 desc="Rövid, szállodából induló kör a legközelebbi tóhoz. Kirchbergen át a Thumsee-hez, a tóparton a Seewirtig, és egy másik úton vissza a városba. Ideális érkezésnapi tesztkörnek. (A Listsee felé vezető út meredek, ezért kimaradt.)",
 wps=[HOTEL,(47.7232,12.8726,"Alte Saline – sólepárló","history"),(47.7193,12.8219,"Thumsee","lake","via"),(47.7126,12.8145,"Nesselgraben (sóvezeték)","history","hl"),HOTEL],
 photos=["Thumsee", "Thumsee Bad Reichenhall", "Alte Saline Bad Reichenhall"],
 car="thumsee", train=("kirch",None),
 warn=["A Thumsee körül októberben sok a gyalogos – lassíts a part menti szakaszon.",
       "A Saalachsee gátján keskeny az út – lassíts, ha gyalogosok jönnek."]),
# ------------------------------------------------------------------ 2
dict(id="frillensee-falkensee", name="Frillensee–Falkensee–Listsee", creative=False, rating=5,
 inspired=dict(komoot=30929451, km=40),
 desc="A környék klasszikus „hármas tó” köre. A Listsee után a Zwiesel lábánál erdei murvautakon kapaszkodsz fel a rejtett Frillensee-hez, majd Adlgaßon át a Falkensee lápos medencéjéhez gurulsz Inzell szélén. Visszafelé a Weißbach völgyén és a Thumsee-n át érsz haza. Sok árnyékos erdő, kevés forgalom.",
 wps=[HOTEL,(47.7368,12.8450,"Listsee","lake","via"),(47.7657,12.8173,"Frillensee","lake","via"),(47.7745,12.7983,"Forsthaus Adlgaß","hut"),(47.7482,12.7664,"Falkensee","lake","via"),(47.7116,12.7850,"Mauthäusl","hut"),(47.7193,12.8219,"Thumsee","lake","via"),HOTEL],
 photos=["Frillensee Inzell","Falkensee Inzell","Listsee","Thumsee"],
 car="thumsee", train=("kirch",None),
 warn=["A Frillensee 950 m körül van: hideg reggeleken deres, csúszós lehet az erdei út.",
       "Forsthaus Adlgaß – októberben rövidített nyitvatartás, ne erre építs ebédet."]),
# ------------------------------------------------------------------ 3
dict(id="stoisser-alm", name="Stoißer Alm–Frillensee", creative=False, rating=5,
 inspired=dict(komoot=1120085034, km=55),
 desc="Panorámás, erős félnapos kör a Teisenberg és a Hochstaufen között. Pidingen és Angeren át a Stoißberg falvain kapaszkodsz fel a Stoißer Almig (kilátás a Rupertiwinkelre és a Chiemgaura), majd erdei utakon Adlgaß és a Frillensee felé ereszkedsz, és a Thumsee-n át zárod a kört.",
 wps=[HOTEL,(47.7596,12.9114,"Piding","town"),(47.8039,12.8559,"Anger","town"),(47.8057,12.8369),(47.8037,12.7716,"Stoißer Alm","hut"),(47.7745,12.7983,"Forsthaus Adlgaß","hut"),(47.7657,12.8173,"Frillensee","lake","via"),(47.7368,12.8450,"Listsee","lake","via"),HOTEL],
 photos=["Stoißer Alm","Teisenberg","Frillensee Inzell"],
 car="anger", train=("piding",None),
 warn=["A Stoißer Alm (≈1270 m) felett már lehet hó vagy jég – ellenőrizd az előrejelzést.",
       "Hosszú, hűvös lejtő Adlgaß felé: vigyél széldzsekit és hosszú ujjú kesztyűt."]),
# ------------------------------------------------------------------ 4
dict(id="untersberg-menten", name="Untersberg mentén Salzburg kapujáig", creative=False, rating=4,
 inspired=dict(komoot=1109509177, km=50),
 desc="Lankás, könnyű kör az Untersberg északi lábánál. Großgmainból a határ mentén Fürstenbrunnba, a Glanegg-kastélyhoz és Grödigen át a hellbrunni kastélyparkig gurulsz, visszafelé a Leopoldskroner Moos lápréti útjain és Walson át érsz haza. Jó választás borús napra, amikor a hegyek felhőben vannak.",
 wps=[HOTEL,(47.7296,12.9180,"Großgmain","town"),(47.7433,12.9915,"Fürstenbrunn – Untersberg-márvány","history"),(47.7496,13.0083,"Schloss Glanegg","history","via"),(47.7633,13.0644,"Schloss Hellbrunn","history","via"),(47.7858,13.0387,"Leopoldskroner Weiher","lake","via"),(47.7811,12.9842,"Viehhausen","town"),HOTEL],
 photos=["Untersberg","Schloss Hellbrunn","Leopoldskroner Weiher","Schloss Glanegg"],
 car="grossgmain", train=("brh",None),
 warn=["Hellbrunn környékén hétvégén sok gyalogos és turistabusz.",
       "Határátlépés Großgmainnál – vigyél személyi igazolványt."]),
# ------------------------------------------------------------------ 5
dict(id="teisendorf", name="Rupertiwinkel – Höglwörth és Teisendorf", creative=False, rating=4,
 inspired=dict(komoot=1037421873, km=59),
 desc="Dombos, falusi hangulatú kör a Rupertiwinkelben. Angeren át a Höglwörther See kolostoráig (kolostorkocsma!), majd mezőgazdasági utakon Teisendorfba és Neukirchen am Teisenbergbe tekersz. Visszafelé a Teisenberg lábán, majd Anger és Piding felé gurulsz. Sok rövid, éles emelkedő, gyönyörű kilátás a Staufenre.",
 wps=[HOTEL,(47.7596,12.9114,"Piding","town"),(47.8156,12.8429,"Höglwörther See – kolostor","history","via"),(47.8493,12.8343,"Teisendorf","town"),(47.8336,12.7422,"Neukirchen am Teisenberg","town"),(47.8039,12.8559,"Anger","town"),HOTEL],
 photos=["Höglwörth","Teisendorf","Höglwörther See"],
 car="anger", train=("teis","Teisendorfról is indítható (BR → Freilassing → Teisendorf, ~35 perc, átszállással)."),
 warn=["Októberben trágyázási/szüreti forgalom a mezőgazdasági utakon – sáros lehet a burkolat.",
       "A Klosterwirt Höglwörth hétfőn-kedden gyakran zárva."]),
# ------------------------------------------------------------------ 6
dict(id="staufen-kor", name="Hochstaufen-kör", creative=False, rating=4,
 inspired=dict(komoot=1053575264, km=69),
 desc="A Staufen-masszívum teljes megkerülése. Pidingen és Angeren át a Stoißberg alatti dombokon nyugatra fordulsz, Inzell felé ereszkedsz, majd Weißbachon és a Mauthäuslon át a Saalach völgyébe érsz vissza. Változatos: lankás rétek északon, szűk erdős völgyek délen.",
 wps=[HOTEL,(47.7596,12.9114,"Piding","town"),(47.8039,12.8559,"Anger","town"),(47.8336,12.7422,"Neukirchen am Teisenberg","town"),(47.7622,12.7517,"Inzell","town"),(47.7290,12.7597,"Himmelsleiter (sóvezeték)","history"),(47.7116,12.7850,"Mauthäusl","hut"),(47.7193,12.8219,"Thumsee","lake","via"),HOTEL],
 photos=["Hochstaufen","Inzell","Thumsee"],
 car="anger", train=("piding",None),
 warn=["Inzell és Weißbach között rövid szakaszon a forgalmasabb B305 közelében haladsz – láthatósági mellény ajánlott.",
       "Rövid nappal: indulj legkésőbb 10-kor."]),
# ------------------------------------------------------------------ 7
dict(id="aschauer-klamm-lofer", name="Aschauer Klamm–Lofer", creative=False, rating=4,
 inspired=dict(komoot=1175420631, km=100),
 desc="Egész napos völgyi túra a Saalach mentén Loferig. A Saalachsee után a régi völgyi utakon Schneizlreuthba, majd a Mußbach és az Aschauer Klamm erdei útjain Melleckhez érsz, átlépsz Ausztriába, és a Tauernradweg Saalach-szakaszán Unkenen át Loferig tekersz. Visszafelé a folyó túlsó partján, ahol lehet, más úton.",
 wps=[HOTEL,(47.7086,12.8573,"Saalachsee","lake"),(47.6905,12.7999,"Schneizlreuth","town"),(47.6806,12.7811,"Mußbach-völgy","gorge"),(47.6713,12.7848,"Aschauer Klamm","gorge"),(47.6720,12.7581,"Melleck","town"),(47.6443,12.7189,"Unken","town"),(47.5868,12.6950,"Lofer","town"),(47.6480,12.7300),(47.7116,12.7850,"Mauthäusl","hut"),HOTEL],
 photos=["Aschauer Klamm","Saalachsee","Lofer","Unken Salzburg"],
 car="unken", train=("brh",None),
 warn=["Az Aschauer Klamm gyalogos szurdokösvényét a track megkerüli az erdei úton – a szurdok bejáratánál érdemes 15 percre letenni a bringát.",
       "Lofer után a visszaút 50 km – 15 óra után már ne fordulj tovább dél felé."]),
# ------------------------------------------------------------------ 8
dict(id="hoegl", name="Högl-dombhát", creative=False, rating=3,
 inspired=dict(komoot=1120085549, km=28),
 desc="Rövid, kilátásos kör a Högl dombhátán, a Salzach-medence és a Berchtesgadeni-Alpok panorámájával. Pidingről a Johannishöglre kapaszkodsz, a dombtetőn Ulrichshögl kápolnája mellett haladsz, majd Aufhamon át ereszkedsz vissza. Délutáni rövid körnek tökéletes.",
 wps=[HOTEL,(47.7596,12.9114,"Piding","town"),(47.7914,12.9232,"Johannishögl","view","via"),(47.8095,12.9249,"Ulrichshögl","view","via"),(47.8083,12.9000,"Högl","view","hl"),(47.7830,12.8680),HOTEL],
 photos=["Högl Anger","Johannishögl","Ulrichshögl"],
 car="anger", train=("piding",None),
 warn=["A Johannishögl Berggasthof októberben hétköznap rövidebben tart nyitva."]),
# ------------------------------------------------------------------ 9
dict(id="untersberg-kor", name="Untersberg-kör", creative=False, rating=5,
 inspired=dict(komoot=1035527445, km=59, bergfex=2307368),
 desc="A környék egyik legszebb klasszikusa: az Untersberg teljes megkerülése. Hallthurmon át Bischofswiesenbe és Berchtesgadenbe, onnan az Almbachklamm és Marktschellenberg felé, majd St. Leonhardon, Grödigen és Fürstenbrunnon át Großgmain felé zárod a kört. Két országon át, sziklafalak alatt.",
 wps=[HOTEL,(47.7197,12.9004,"Bayerisch Gmain","town"),(47.6966,12.9354,"Hallthurm","pass"),(47.6520,12.9604,"Bischofswiesen","town"),(47.6263,12.9993,"Berchtesgaden","town"),(47.6661,13.0346,"Almbachklamm","gorge"),(47.6970,13.0450,"Marktschellenberg","town"),(47.7262,13.0444,"St. Leonhard – Untersbergbahn","view"),(47.7433,12.9915,"Fürstenbrunn","history"),(47.7296,12.9180,"Großgmain","town"),HOTEL],
 photos=["Untersberg","Almbachklamm","Marktschellenberg","Hallthurm"],
 car="hallthurm", train=("bgd","Berchtesgadenből is indítható (~30 perc vonattal), így a kör bármelyik pontján kezdhető."),
 warn=["Berchtesgaden–Marktschellenberg között a B305 rövid szakaszán forgalom van.",
       "Határátlépés Marktschellenbergnél – személyi igazolvány."]),
# ------------------------------------------------------------------ 10
dict(id="hintersee-strubklamm", name="Wiestal–Strubklamm–Hintersee (Flachgau)", creative=False, rating=4,
 inspired=dict(komoot=1223393682, km=58),
 desc="Halleinből a Wiestal víztározója és a Strubklamm sziklaszurdoka mentén kapaszkodsz fel Faistenauba, majd a Flachgau kevéssé ismert, gyönyörű Hintersee-jéhez. Visszafelé Faistenaun és Ebenaun át, a Wiestal völgyében gurulsz vissza Halleinbe – a meredek gaißaui lejtőt elkerülve.",
 wps=[(47.6849,13.0992,"Hallein Bahnhof","station"),(47.7177,13.1352,"Wiestal","lake"),(47.7496,13.1709,"Wiestalstausee","lake","via"),(47.7822,13.1793,"Strubklamm","gorge","via"),(47.7750,13.2280,"Faistenau","town"),(47.7488,13.2476,"Hintersee","lake","via"),(47.7750,13.2280,"Faistenau","town"),(47.7830,13.1700,"Ebenau","town"),(47.7177,13.1352),(47.6849,13.0992)],
 photos=["Strubklamm","Hintersee Flachgau","Wiestalstausee","Faistenau"],
 car="hallein", train=("hallein","BR → Salzburg Hbf (S-Bahn) → Hallein (S3), kb. 55 perc."),
 warn=["A Wiestal Landesstraße rövid szakaszán forgalom van – a völgyben, ahol lehet, a kerékpárúton haladj.",
       BIKE_TICKET_AT]),
# ------------------------------------------------------------------ 11
dict(id="haunsberg", name="Haunsberg és a Salzach", creative=False, rating=3,
 inspired=dict(komoot=1033799113, km=39),
 desc="Freilassingtól a Salzach osztrák partján, Bergheimen és Antheringen át a Haunsberg erdős gerincére kapaszkodsz (Kaiserbuche), majd Oberndorfba – a „Csendes éj” kápolnájához – ereszkedsz, és a Salzach-gáton gurulsz vissza. Könnyű-közepes, vonattal vagy autóval is jól elérhető.",
 wps=[(47.8366,12.9771,"Freilassing Bahnhof","station"),(47.8526,13.0029,"Saalachspitz","view"),(47.8396,13.0207,"Bergheim","town"),(47.8795,13.0010,"Anthering","town"),(47.9266,13.0087,"Kaiserbuche (Haunsberg)","view","via"),(47.9419,12.9439,"Oberndorf – Stille-Nacht-kápolna","history","via"),(47.8366,12.9771)],
 photos=["Haunsberg","Stille-Nacht-Kapelle Oberndorf","Salzach Laufen Oberndorf"],
 car="freil", train=("freil","BR → Freilassing, 15 perc, óránként."),
 warn=[BIKE_TICKET_DE, "A Haunsberg erdészeti útjain októberben fakitermelés lehet – figyeld a lezárás-táblákat."]),
# ------------------------------------------------------------------ 12
dict(id="alte-postalmstrasse", name="Alte Postalmstraße – vonattal Gollingig", creative=True, rating=5,
 inspired=dict(komoot=1229213372, km=130),
 desc="Kreatív, egész napos kaland: vonattal Gollingig, onnan a Lammer völgyén a Lammeröfen szurdokhoz, majd Voglaunál a régi, murvás Postalmstraße serpentinjein Európa egyik legnagyobb alpesi legelőjére, a Postalmra (≈1300 m). Lefelé az új aszfaltúton Abtenau felé, majd a Lammertalon vissza Gollingba és vonattal haza.",
 wps=[(47.6002,13.1647,"Golling-Abtenau Bahnhof","station"),(47.5880,13.2700,"Lammeröfen / Lammerklamm","gorge"),(47.5933,13.3111,"Voglau","town"),(47.6017,13.2974,"Alte Postalmstraße","pass"),(47.6530,13.4310,"Postalm","hut"),(47.6550,13.4390),(47.5637,13.3460,"Abtenau","town"),(47.5880,13.2650),(47.6002,13.1647)],
 photos=["Postalm","Lammeröfen","Abtenau","Postalmstraße"],
 car=None, train=("golling","BR → Salzburg Hbf (S-Bahn, ~30 perc) → Golling-Abtenau (S3, ~35 perc). Visszaút ugyanígy, óránként."),
 warn=["A Postalm ≈1300 m: október elején reggel fagy, akár friss hó is lehet – nézd meg a webkamerát indulás előtt.",
       "A Postalm kunyhóinak egy része október közepétől zár; vigyél elég ételt.",
       BIKE_TICKET_DE+" "+BIKE_TICKET_AT]),
# ------------------------------------------------------------------ 13
dict(id="hirschbichl-lofer", name="Hirschbichl-hágó–Lofer nagy kör", creative=False, rating=5,
 inspired=dict(komoot=1431200842, km=134),
 desc="A nagy királyetap: Hallthurmon és Bischofswiesenen át Ramsauba, a Hintersee mellett a Klausbachtal nemzeti parki murvaútján fel a Hirschbichl-hágóra (1183 m), le Weißbach bei Loferbe a Seisenbergklamm mellett, majd a Saalach völgyén Loferen, Unkenen és Melleck-en át vissza. Hosszú, de a táj mindent visz.",
 wps=[HOTEL,(47.6966,12.9354,"Hallthurm","pass"),(47.6520,12.9604,"Bischofswiesen","town"),(47.6068,12.9026,"Ramsau","town"),(47.6067,12.8541,"Hintersee (Ramsau)","lake","via"),(47.6051,12.8583,"Klausbachtal","gorge"),(47.5528,12.7947,"Hirschbichl-hágó","pass"),(47.5224,12.7510,"Seisenbergklamm","gorge","via"),(47.5868,12.6950,"Lofer","town"),(47.6443,12.7189,"Unken","town"),(47.6720,12.7581,"Melleck","town"),(47.7086,12.8573,"Saalachsee","lake"),HOTEL],
 photos=["Hirschbichl","Hintersee Ramsau","Klausbachtal","Seisenbergklamm"],
 car="hintersee", train=("bgd","Rövidítés: vonattal Berchtesgadenig (~30 perc), onnan Ramsau felé – kb. 25 km-rel rövidebb."),
 warn=["A Hirschbichl 1183 m: október elején hó/jég lehetséges, a nemzeti parki úton busz is jár (Almerlebnisbus, általában okt. közepéig).",
       "A Klausbachtal felső szakasza meredek (12–15%), murvás – erős áttétel kell.",
       "Napnyugta 18:50 körül: indulj 8:30-ig, lámpa legyen nálad."]),
# ------------------------------------------------------------------ 14
dict(id="saalach-mussbach", name="Saalach–Mußbach kör", creative=False, rating=3,
 inspired=dict(guide="Gravelbiken rund um Bad Reichenhall"),
 desc="Csendes völgyi kör a Saalach mentén délre. A Saalachsee gátja után a régi völgyi utakon Jettenbergbe, majd a Mußbach erdei murvaútján kapaszkodsz, és a folyó túlsó partján gurulsz vissza. Kevés szint, sok murva – kezdőknek is jó.",
 wps=[HOTEL,(47.7086,12.8573,"Saalachsee","lake"),(47.6905,12.7999,"Schneizlreuth","town"),(47.6806,12.7811,"Mußbach","gorge","via"),(47.6711,12.7940,"Oberjettenberg","view"),(47.7126,12.8145,"Nesselgraben (sóvezeték)","history","via"),HOTEL],
 photos=["Saalachsee","Saalach Bad Reichenhall","Schneizlreuth"],
 car="thumsee", train=("kirch",None),
 warn=["A Saalach menti utat esőzés után helyenként elmossa a víz – ilyenkor maradj a B21 melletti kerékpárúton."]),
# ------------------------------------------------------------------ 15
dict(id="mordaualm", name="Schwarzbachwacht-hágó – Ramsau kör", creative=False, rating=4,
 inspired=dict(guide="Gravelbiken rund um Bad Reichenhall"),
 desc="Hegyi félnapos: a Saalachsee mellől a Schwarzbach völgyén, egyenletes aszfaltúton a Schwarzbachwacht-hágóra (868 m), le Ramsauba, majd Bischofswiesenen és Hallthurmon át haza. A Reiter Alpe és a Watzmann között. A Mordaualm meredek (12% feletti) murvás feljárója kimaradt – a hágóról gyalogos kitérőként érhető el.",
 wps=[HOTEL,(47.7086,12.8573,"Saalachsee","lake"),(47.6711,12.7940,"Oberjettenberg","view"),(47.6368,12.8552,"Schwarzbachwacht","pass"),(47.6309,12.8712,"Mordau","town","hl"),(47.6475,12.8893,"Mordaualm","hut","hl"),(47.6188,12.8817,"Taubensee (Ramsau)","lake"),(47.6520,12.9604,"Bischofswiesen","town"),(47.6966,12.9354,"Hallthurm","pass"),HOTEL],
 photos=["Mordaualm","Schwarzbachwacht","Taubensee Ramsau","Reiter Alpe"],
 car="hallthurm", train=("bischof","Bischofswiesenből is indítható (~22 perc vonattal)."),
 warn=["A Mordaualm kunyhói (Hinterkeilhofkaser) általában szeptember végén–október elején zárnak.",
       "A Schwarzbachwacht felé a B305 forgalmas, szűk – ha van mellette erdei út, a track azt használja."]),
# ------------------------------------------------------------------ 16
dict(id="watzmann-koenigssee", name="Watzmann–Königssee kör", creative=False, rating=5,
 inspired=dict(guide="Gravelbiken around Thumsee"),
 desc="Berchtesgadeni képeslap-kör: a vasútállomástól a Königssee partjára (Malerwinkel!), Schönauon át az Engedey felé, majd a Wimbachbrücke és Ramsau templomának ikonikus nézőpontja után a Soleleitungsweg történelmi sóvezeték-útjának bringával járható szakaszán (Zipfhäusl) haladsz, és Ilsanknál a Ramsauer Ache völgyében gurulsz vissza Berchtesgadenbe. Rövid, de minden kanyarban Watzmann.",
 wps=[(47.6263,12.9993,"Berchtesgaden Hbf","station"),(47.5918,12.9895,"Königssee","lake","via"),(47.5828,12.9928,"Malerwinkel","view"),(47.6030,12.9232,"Wimbachbrücke","gorge"),(47.6068,12.9026,"Ramsau – Pfarrkirche","view"),(47.6175,12.8954,"Zipfhäusl – Soleleitungsweg","history"),(47.6068,12.9026,"Ramsau","town"),(47.6150,12.9400,"Ilsank – Ramsauer Ache","gorge"),(47.6263,12.9993)],
 photos=["Königssee","Malerwinkel Königssee","Ramsau Pfarrkirche Watzmann","Soleleitungsweg Berchtesgaden"],
 car="koenigssee", train=("bgd","BR → Berchtesgaden Hbf, ~30 perc, óránként."),
 warn=["A Königssee-parton hétvégén nagyon sok a gyalogos – a Seelände környékén told a bringát.",
       "A Soleleitungsweg Gerstreit–Berchtesgaden szakasza gyalogosoknak fenntartott, kerékpárral tilos – a track ezt elkerüli; a járható részen is csengess.", BIKE_TICKET_DE]),
# ------------------------------------------------------------------ 17
dict(id="roethelmoos-weitsee", name="Röthelmoos–Weitsee tóvidék", creative=False, rating=5,
 inspired=dict(guide="Gravelbiken around Thumsee"),
 desc="Inzellből Ruhpoldingon át az Urschlauer Achen völgyén fel a Röthelmoos lápos almvidékére, onnan erdészeti utakon le a Chiemgau „kanadai” tóláncához: Weitsee, Mittersee, Lödensee, Förchensee. A Laubau és a Taubensee érintésével gurulsz vissza Inzellbe. Az egyik legszebb gravel-terep a régióban.",
 wps=[(47.7622,12.7517,"Inzell","town"),(47.7376,12.6685,"Taubensee (Ruhpolding)","lake"),(47.7621,12.6488,"Ruhpolding","town"),(47.7350,12.6000),(47.7150,12.5600,"Röthelmoos","hut"),(47.6826,12.5604,"Weitsee","lake","via"),(47.6902,12.5855,"Mittersee","lake","via"),(47.6939,12.5946,"Lödensee","lake","via"),(47.7258,12.6580,"Laubau","hut"),(47.7622,12.7517)],
 photos=["Röthelmoos","Weitsee","Lödensee","Mittersee Ruhpolding"],
 car="inzell", train=("ruhp","Vonattal hosszú (Traunsteinen át ~1,5 óra) – autó javasolt."),
 warn=["A Röthelmoos almjai október elején zárnak (jellemzően a hónap első felében) – vízről, ételről gondoskodj.",
       "A Röthelmoos erdészeti útja 900 m fölé visz: deres reggeleken csúszós.",
       "A B305 Seehaus–Ruhpolding szakaszán, ahol lehet, a párhuzamos kerékpárúton haladj."]),
# ------------------------------------------------------------------ 18
dict(id="rossfeld", name="Rossfeld-panorámaút – vonattal oda, bringával haza", creative=True, rating=5,
 inspired=None,
 desc="Vonattal Berchtesgadenbe, onnan Oberaun át fel a Rossfeld-panorámaútra (≈1550 m, Németország egyik legmagasabb útja) – a Tennengebirge és a Dachstein felett. A Zinken alatt Bad Dürrnbergbe és Halleinbe ereszkedsz, majd a Salzach és az Untersberg lábán, Grödigen és Großgmainon át tekersz haza a szállodáig.",
 wps=[(47.6263,12.9993,"Berchtesgaden Hbf","station"),(47.6450,13.0450,"Oberau","town"),(47.6514,13.0618,"Rossfeld – Skihütte","view","via"),(47.6312,13.0929,"Rossfeld Almkiosk – panoráma","view","via"),(47.6494,13.0889,"Zinken","view"),(47.6661,13.0900,"Bad Dürrnberg – sóbánya","history","via"),(47.6849,13.0992,"Hallein","town"),(47.7262,13.0444,"St. Leonhard","town"),(47.7433,12.9915,"Fürstenbrunn","history"),(47.7296,12.9180,"Großgmain","town"),HOTEL],
 photos=["Roßfeldpanoramastraße","Rossfeld Berchtesgaden","Bad Dürrnberg","Hallein"],
 car=None, train=("bgd","BR → Berchtesgaden Hbf, ~30 perc, majd bringával haza."),
 warn=["A Rossfeld 1500 m felett: október elején hó és jegesedés valószínű – webkamera, és ha havas, fordulj Oberauból Marktschellenberg felé.",
       "A panorámaút autós fizetős út, hétvégén motoros forgalom.", BIKE_TICKET_DE]),
# ------------------------------------------------------------------ 19
dict(id="loferer-alm", name="Lofer – Vorderkaserklamm – Unken (Saalach-völgy)", creative=False, rating=4,
 inspired=dict(guide="Gravelbiken around Thumsee"),
 desc="Loferből St. Martinon át a Vorderkaserklamm szurdokához (büfé, rövid gyalogos kör a szurdokban), majd vissza Loferbe és a Saalach-völgyi bringaúton (Tauernradweg) Unkenig és vissza. Lankás, a Loferer Steinberge falai alatt. A Loferer Alm meredek (12% feletti) hegyi útja kimaradt.",
 wps=[(47.5868,12.6950,"Lofer","town"),(47.5678,12.7049,"St. Martin bei Lofer","town"),(47.5214,12.7040,"Vorderkaserklamm","gorge","via"),(47.5678,12.7049),(47.6443,12.7189,"Unken","town","via"),(47.5868,12.6950)],
 photos=["Loferer Alm","Vorderkaserklamm","Lofer","Loferer Steinberge"],
 car="lofer", train=("brh","Vonattal nem érhető el – autó (30 perc) vagy hosszabb változat bringával a Saalach mentén."),
 warn=["A Saalach-völgyi bringaúton hétvégén sok a kiránduló – csengess.",
       "A Vorderkaserklamm és a büfé általában október közepéig nyitva."]),
# ------------------------------------------------------------------ 20
dict(id="soleleitung-traunstein", name="A sólé útja – 400 éves sóvezeték Traunsteinig", creative=True, rating=5,
 inspired=None,
 desc="Kreatív történelmi túra a 1619-ben épült sóvezeték (Soleleitung) nyomvonalán: a reichenhalli Alte Salinétól a Nesselgraben és az Antoniberg mentén, a Mauthäuslon és a Himmelsleiter lépcsője mellett (a lépcső kitérő gyalog), majd Inzellen és a Weiße Traun völgyén, Siegsdorfon át a Traun-parti bringaúton Traunsteinig, a sólé egykori céljáig. Haza vonattal.",
 wps=[HOTEL,(47.7232,12.8726,"Alte Saline – a sóvezeték kezdete","history"),(47.7126,12.8145,"Nesselgraben","history","via"),(47.7114,12.8115,"Antoniberg","history"),(47.7116,12.7850,"Mauthäusl – brunnhaus","history"),(47.7290,12.7597,"Himmelsleiter","history","hl"),(47.7622,12.7517,"Inzell","town"),(47.7885,12.7201,"Fantenberg","town"),(47.8220,12.6450,"Siegsdorf","town"),(47.8565,12.6382,"Traun-parti bringaút (Haslacher Steg)","view","via"),(47.8650,12.6480,"Traun-part, Haferlbrücke","view","via"),(47.8687,12.6436,"Traunstein óváros – Stadtplatz","history","hl"),(47.8694,12.6390,"Traunstein Bahnhof","station")],
 photos=["Soleleitung Bad Reichenhall Traunstein","Himmelsleiter Weißbach","Alte Saline Bad Reichenhall","Traunstein Stadtplatz"],
 car=None, train=("traun","Visszaút: Traunstein → Freilassing → Bad Reichenhall, kb. 60 perc, óránként (átszállás Freilassingban)."),
 warn=["A Himmelsleiter lépcsős – a track a mellette futó úton kerüli meg, de a lépcső tetején érdemes megállni.",
       BIKE_TICKET_DE]),
# ------------------------------------------------------------------ 20b
dict(id="soleleitung-oda-vissza", variant_of="soleleitung-traunstein", name="A sólé útja oda-vissza – Traunstein és vissza bringával", creative=True, rating=4,
 inspired=None,
 desc="Kreatív történelmi túra a 1619-ben épült sóvezeték (Soleleitung) nyomvonalán: a reichenhalli Alte Salinétól a Nesselgraben és az Antoniberg mentén, a Mauthäuslon és a Himmelsleiter lépcsője mellett (a lépcső kitérő gyalog), majd Inzellen és a Weiße Traun völgyén, Siegsdorfon át a Traun-parti bringaúton Traunsteinig, a sólé egykori céljáig. Vissza is bringával, de könnyebben: Traunsteintől a Rupertiwinkel lankás, kis forgalmú útjain és kerékpárútjain Teisendorfon, Angeren és Pidingen át a szállodáig – a sóvezeték hegyes szakaszát (Mauthäusl, Inzell) nem kell még egyszer megmászni. A visszaút kb. 38 km és 300 m szint, 90% felett aszfalt, szinte végig falusi mellékutakon; különálló kerékpárút ezen a vonalon kevés van.",
 wps=[HOTEL,(47.7232,12.8726,"Alte Saline – a sóvezeték kezdete","history"),(47.7126,12.8145,"Nesselgraben","history","via"),(47.7114,12.8115,"Antoniberg","history"),(47.7116,12.7850,"Mauthäusl – brunnhaus","history"),(47.7290,12.7597,"Himmelsleiter","history","hl"),(47.7622,12.7517,"Inzell","town"),(47.7885,12.7201,"Fantenberg","town"),(47.8220,12.6450,"Siegsdorf","town"),(47.8565,12.6382,"Traun-parti bringaút (Haslacher Steg)","view","via"),(47.8687,12.6436,"Traunstein óváros – Stadtplatz (400 m gyalog fel)","history","hl"),(47.8650,12.6480,"Traun-part, Haferlbrücke – forduló","town","via")],
 wps_back=[(47.8493,12.8343,"Teisendorf","town"),(47.8039,12.8559,"Anger","town"),(47.7596,12.9114,"Piding","town"),HOTEL],
 photos=["Soleleitung Bad Reichenhall Traunstein","Himmelsleiter Weißbach","Alte Saline Bad Reichenhall","Traunstein Stadtplatz"],
 car=None, train=None,
 warn=["Vészkijárat: ha elfáradsz, Traunsteinből vagy Teisendorfból vonattal is hazajöhetsz (Freilassingon át, 35–60 perc; kerékpárjegy kell).", "A Himmelsleiter lépcsős – a track a mellette futó úton kerüli meg, de a lépcső tetején érdemes megállni.",
       "Hosszú nap: 9 óra előtt indulj, Traunsteinben legkésőbb 13:30-kor fordulj vissza.", "A visszaút főleg aszfalt – Teisendorf és Anger között rövid szakaszon forgalmasabb úton is haladhatsz, ott figyelj."]),
# ------------------------------------------------------------------ 21
dict(id="salzburg-haza", name="Vonattal Salzburgba, bringával haza (WOSSA 1 ihlette)", creative=True, rating=4,
 inspired=dict(wossa="WOSSA Etappe 1"),
 desc="Reggel S-Bahnnal Salzburgba, kávé a Salzach-parton, aztán a Salzach gátján Hellbrunnig, a Glasenbach-szurdok bejáratáig, majd a Leopoldskroner Moos lápréti útjain, Grödigen és Fürstenbrunnon át az Untersberg lábánál haza. Ajándék nap: egyirányú, majdnem végig lejt vagy sík.",
 wps=[(47.8125,13.0453,"Salzburg Hbf","station"),(47.8000,13.0450,"Salzburg óváros – Salzach","history"),(47.7700,13.0759,"Salzach-gát","view","via"),(47.7633,13.0644,"Schloss Hellbrunn","history","via"),(47.7858,13.0387,"Leopoldskroner Weiher","lake"),(47.7433,12.9915,"Fürstenbrunn","history"),(47.7296,12.9180,"Großgmain","town"),HOTEL],
 photos=["Salzburg Salzach","Schloss Hellbrunn","Leopoldskroner Moos","Untersberg"],
 car=None, train=("sbg","BR → Salzburg Hbf, S-Bahn ~30 perc (Freilassingon át), félóránként-óránként."),
 warn=["A WOSSA eredeti GPX-e (thomaskargl.at) nem volt letölthető ebből a környezetből – ez saját, hasonló szellemű nyomvonal.",
       BIKE_TICKET_AT]),
# ------------------------------------------------------------------ 22
dict(id="salzach-laufen", name="Salzach-ártér–Abtsdorfer See–Laufen", creative=True, rating=4,
 inspired=None,
 desc="Szállodából végig a Saalach-parti bringaúton Freilassingig, a torkolatnál (Saalachspitz) rá a Salzach gátján futó Tauernradwegre, az ártéri erdők mentén észak felé, fürdés helyett kávé az Abtsdorfer See partján, majd Laufen óvárosa – a Salzach-hurokban a híddal Oberndorf felé. Haza vonattal Freilassingon át.",
 wps=[HOTEL,(47.7405,12.8928,"Saalach-parti bringaút","view","via"),(47.8046,12.9676,"Saalach-parti bringaút (Ainring)","view","via"),(47.8366,12.9771,"Freilassing","town"),(47.8524,13.0048,"Saalachspitz – folyótorkolat","view","via"),(47.8675,12.9901,"Salzach-gát – Tauernradweg","view","via"),(47.8968,12.9698,"Salzach-ártér","gorge","via"),(47.9097,12.9070,"Abtsdorfer See","lake"),(47.9377,12.9311,"Laufen – óváros","history","via"),(47.9345,12.9223,"Laufen Bahnhof","station")],
 photos=["Abtsdorfer See","Laufen Salzach","Salzachauen Freilassing","Saalachspitz"],
 car=None, train=("laufen","Visszaút: Laufen → Freilassing → Bad Reichenhall, kb. 45 perc, átszállással."),
 warn=["Az ártéri utak esős idő után sárosak, a Salzach áradásakor egyes szakaszok lezárva.", BIKE_TICKET_DE]),
# ------------------------------------------------------------------ 23
dict(id="waginger-see", name="Waginger See és Tachinger See", creative=True, rating=3,
 inspired=None,
 desc="Hosszú, de lankás egész napos: Teisendorfon át a Rupertiwinkel dombjain a Bajorország legmelegebb fürdőtavaként ismert Waginger See-hez, megkerülöd a Tachinger See-t, majd Laufenen és a Salzach-ártéren át térsz vissza Freilassing felé. Ha elfáradsz, Laufenből vagy Freilassingból vonattal is hazajöhetsz.",
 wps=[HOTEL,(47.7596,12.9114,"Piding","town"),(47.8039,12.8559,"Anger","town"),(47.8493,12.8343,"Teisendorf","town"),(47.9316,12.7273,"Waging am See","town"),(47.9658,12.7433,"Tachinger See","lake","via"),(47.9228,12.7884,"Waginger See – keleti part","lake","via"),(47.9377,12.9311,"Laufen","history"),(47.8366,12.9771,"Freilassing","town"),HOTEL],
 photos=["Waginger See","Tachinger See","Waging am See"],
 car="teis", train=("laufen","Rövidítés: Laufenből (~45 perc) vagy Freilassingból (~15 perc) vonattal haza."),
 warn=["Hosszú, nyílt szakaszok – októberben erős szél lehet a tavak felől.",
       "Rövid nap: Laufenben 15:30 után inkább szállj vonatra."]),
]
